print("Hello Rahma, Ruhama and Saleh")
print("How are you doing?")
print("Rahma said good, then Ruhama also said good")
print("But Saleh did not say anything")
print("Because he is in Michigan, and he does not know what we are talking about")
print("Rahma and Ruhama said, we need to clean up our dad and moms room")
print("Rahma and Ruhama are happy about their parents")